# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/db/schema.rs"
custom_type_derives = [
  "diesel::query_builder::QueryId",
  "Clone",
  "Debug",
  "Serialize",
  "Deserialize",
]
import_types = ["diesel::sql_types::*", "pgvector::sql_types::*"]
generate_missing_sql_type_definitions = false


[migrations_directory]
dir = "/Users/blackprince/Documents/dev/personal/test-html-extractor/migrations"
