version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  document-extraction-pipeline:
    build:
      context: ../
      dockerfile: dockerfile
    container_name: document-extraction-pipeline
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - UPLOAD_DIR=./uploads
      - RUST_BACKTRACE=1
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
  uploads:
